py:
  build: .
  command: python3 test/test_postgresql.py
  # command: python3 bench.py --backend postgresql
  # command: python3 bench.py --backend postgresql_jsonb
  volumes:
    - ./simhash_db:/var/www/simhash_db
    - ./test:/var/www/test
    - ./bench.py:/var/www/bench.py
  links:
    # - elasticsearch
    - postgresql

# elasticsearch:
#   image: elasticsearch:2.2
#   ports:
#     - "14200:9200"

postgresql:
  image: postgres:9.5
  ports:
    - "14232:5432"

